---
id: 86698ad5-5893-4764-84f0-9b1c183a08da
version: 1.0.0
license: Apache-2.0
authors:
  - github_account: ddbj
    name: ddbj-workflow
    affiliation: DNA Data Bank of Japan
  - github_account: suecharo
    name: "Suetake, Hirotaka"
    affiliation: The University of Tokyo
    orcid: 0000-0003-2765-0049
  - github_account: tom-tan
    name: "Tanjo, Tomoya"
    affiliation: National Institute of Genetics
    orcid: 0000-0002-4421-9659
  - github_account: inutano
    name: "Ohta, Tazro"
    affiliation: Database Center for Life Science
    orcid: 0000-0003-3777-5945
  - github_account: yyoshiaki
    name: "Yasumizu, Yoshiaki"
    affiliation: Osaka University
    orcid: 0000-0002-9872-4909
  - github_account: ykohki
    name: "Yamada, Kohki"
workflow:
  name: DAT2-cwl Platanus-b assemble
  readme: "https://raw.githubusercontent.com/pitagora-network/DAT2-cwl/0cd20e1be620ae0817a1aa4286d73b78c89809f0/tool/platanus-b/assemble/README.md"
  language:
    type: CWL
    version: v1.0
  files:
    - url: "https://raw.githubusercontent.com/pitagora-network/DAT2-cwl/0cd20e1be620ae0817a1aa4286d73b78c89809f0/tool/platanus-b/assemble/platanus-b-assemble.cwl"
      target: platanus-b-assemble.cwl
      type: primary
  testing:
    - id: test
      files:
        - url: "https://raw.githubusercontent.com/pitagora-network/DAT2-cwl/0cd20e1be620ae0817a1aa4286d73b78c89809f0/tool/platanus-b/assemble/test-job.yml"
          target: test-job.yml
          type: wf_params
        - url: "https://raw.githubusercontent.com/pitagora-network/DAT2-cwl/0cd20e1be620ae0817a1aa4286d73b78c89809f0/test/data/DRR024501_1.fastq"
          target: DRR024501_1.fastq
          type: other
        - url: "https://raw.githubusercontent.com/pitagora-network/DAT2-cwl/0cd20e1be620ae0817a1aa4286d73b78c89809f0/test/data/DRR024501_2.fastq"
          target: DRR024501_2.fastq
          type: other
